services:
  db: 
    image: mysql:latest 
    restart: always 
    env_file:
      - .env.docker
    ports:
      - "3306:3306" 
    expose:
      - '3306'
    volumes:
      - 'C:/Banco_docker/mysql_data:/var/lib/mysql' 

